### ISSUE TITLE
cannot access ../extensions/*: No such file or directory 

### ISSUE THREAD

**Issue by yambrosov** [continuent/tungsten-replicator#1]
Trying to build from 
https://github.com/continuent/tungsten-replicator/tree/5.0.1

Debian 8.7 
java version "1.7.0_121" 
Apache Ant(TM) version 1.9.4 compiled on October 7 2014

BUILD SUCCESSFUL 
Total time: 22 seconds

################################################################ 
# Creating Replicator release 
################################################################

### Copying component: tungsten-replicator 
# Build source: ../replicator/build/tungsten-replicator 
# Build target: build/tungsten-replicator-5.0.1 
### Creating cluster home 
# Copying cluser-home/conf files 
# Copying cluser-home bin scripts 
# Copying in Ruby configuration libraries 
# Copying in oss-commons libraries 
### Creating tools 
ls: cannot access ../extensions/*: No such file or directory 
### Creating manifest file: build/tungsten-replicator-5.0.1/.manifest

**Comment by mccont** [comment]
Why are you building from that directory?

All you need to do is clone the repo, change into the builder directory and run 'build.sh'

I've just tried that here, and it works fine.

**Comment by yambrosov** [comment]
I'm doing it under directory according to the following steps from docs:
But instead of clone used download as zip for branch 5.0.1

git clone https://github.com/continuent/tungsten-replicator
   cd tungsten-replicator/builder
   ./build.sh

With clone it is works (output artifact created tungsten-replicator-5.0.1.tar.gz)
But warning still exists

### Creating tools
ls: cannot access ../extensions/*: No such file or directory
