### ISSUE TITLE
Tungsten Replicator OSS 5.2.2

### ISSUE THREAD

**Issue by AzaZPPL** [continuent/tungsten-replicator#12]
When can we expect Tungsten Replicator OSS 5.2.2?

**Comment by mccont** [comment]
Is there something in particular you are expecting to see in 5.2.2>

**Comment by AzaZPPL** [comment]
There are differences in release notes for Tungsten Replicator 5.2.1 and Tungsten Replicator OSS 5.2.1. In the non OSS version there are a lot more fixes than in the OSS version.

For example.
In the release notes it shows that issue CT-348 has been fixed in Tungsten Replicator 5.2.1. If you check the release notes of Tungsten Replicator OSS 5.2.1 it has not been fixed in this version.

**Comment by mccont** [comment]
Correct. There are fixes in the commercial release that do not apply to the
OSS release.

For example, tpm diag (CT-348) is used to generate a support packet for the
Continuent support team. Since the OSS release is an unsupported product,
there is no need to fix this issue in the OSS release.

**Comment by AzaZPPL** [comment]
Aha I see, I thought these were supposed to be included. Thanks for the clarification.
