### ISSUE TITLE
Connection reset by peer on debian 8.7 through ruby net ssh

### ISSUE THREAD

**Issue by yambrosov** [continuent/tungsten-replicator#2]
Hello

I installed all requisites and wont to install multimaster on debian 8.7
If i run this cmd from putty (from windows) all works.

./tools/tpm install epsilon --topology=all-masters --install-directory=/opt/continuent --replication-user=root --replication-password=12345678 --master=nodeone,nodetwo --members=nodeone,nodetwo --master-services=alpha,beta --skip-validation-check=MySQLMyISAMCheck --verbose --start

But if i started it from net-ssh-v4.1.0, i catch attached error
[tungsten-configure.txt](https://github.com/continuent/tungsten-replicator/files/875573/tungsten-configure.txt)

Also i added unsupported ciphers on nodes to prevent such error
Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,blowfish-cbc,aes128-cbc,3des-cbc,cast128-cbc,arcfour,aes192-cbc,aes256-cbc'

Mar 28 06:20:42 nodetwo sshd[1244]: fatal: no matching cipher found: client aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se,idea-cbc,none,arcfour128,arcfour256 server aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com [preauth]

errors links to unsupported encryption algorithms, as i understand
here is logs from ssh-debug activities
[auth-node1.txt](https://github.com/continuent/tungsten-replicator/files/875596/auth-node1.txt)
[auth-node2.txt](https://github.com/continuent/tungsten-replicator/files/875597/auth-node2.txt)

**Comment by mccont** [comment]
Hi, 

Yes, there are some known issues with compatibility between the various net-ssh versions and ruby. 

I haven't applied the changes up here to the open source repo, but the solution we have developed is actually to remove the bundled net-ssh libraries and instead install net-ssh and net-sap using ruby gems. 

Let me see if I can move those changes up here. 

MC

**Comment by yambrosov** [comment]
Hi,
Do you have any update about this ? Is it possible to get workaround maybe?

**Comment by mccont** [comment]
Apologies, I fully intended to push the changes last week. 

I've just pushed them now. 

Please make sure you have install rubygems, and used rubygems to install net/ssh and net/scp. For example: 

gem install net-ssh
gem install net-scp

**Comment by yambrosov** [comment]
Hi
Thank you 
With 
net-scp (1.2.1)
net-ssh (4.1.0)
ruby 2.0.0p643

i got:

ERROR >> uninitialized constant SSHConnections::Net
DEBUG >> uninitialized constant SSHConnections::Net
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configurator.rb:1763:in `rescue in ssh_result'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configurator.rb:1682:in `ssh_result'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configurator.rb:1813:in `ssh_result'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configure/modules/package_cluster.rb:1302:in `block (2 levels) in get_deployment_configuration'
/home/tungsten/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configure/modules/package_cluster.rb:1301:in `block in get_deployment_configuration'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configure/modules/package_cluster.rb:1299:in `each'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configure/modules/package_cluster.rb:1299:in `get_deployment_configuration'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configure/configure_command.rb:1178:in `block (3 levels) in build_deployment_configurations'

**Comment by yambrosov** [comment]
with 

net-scp (1.2.1)
net-ssh (2.7.0)
ruby 2.0.0p643

such error :
ERROR >> nodetwo >> Failed: scp /tmp/tcfg20170403-1330-1m7ll0c tungsten@nodetwo:/tmp/tungsten-replicator-5.0.1_pid1330//.tungsten.cfg, RC: , Result: , No STDERR
DEBUG >> nodetwo >> Failed: scp /tmp/tcfg20170403-1330-1m7ll0c tungsten@nodetwo:/tmp/tungsten-replicator-5.0.1_pid1330//.tungsten.cfg, RC: , Result: , No STDERR
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configurator.rb:1969:in `rescue in scp_result'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configurator.rb:1948:in `scp_result'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configure/configure_deployment_handler.rb:80:in `prepare_config'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configure/configure_deployment_handler.rb:19:in `block in prepare'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configure/configure_deployment_handler.rb:15:in `each'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configure/configure_deployment_handler.rb:15:in `prepare'
/opt/tungsten/tungsten-replicator-5.0.1/tools/ruby-tpm/configure/configure_command.rb:608:in `block (2 levels) in parallel_handle'

which versions should be used ?

**Comment by yambrosov** [comment]
With 
net-scp (1.1.0)
net-ssh (2.7.0)
ruby 2.0.0p643

It is ok

**Comment by mccont** [comment]
Yes, unfortunately there are compatibility issues with net-ssh on different Ruby versions which are outside of our control. There are some very specific version requirements with each Ruby revision.

**Comment by mccont** [comment]
I pushed up the changes for net/ssh and net/scp use last week, have you been able to try it again? with the updated version?

**Comment by yambrosov** [comment]
Hi, i tested new version it is ok when install through putty, but when installing using net-ssh (with th esame version) - i got an error, seems problem in net-ssh gem
https://github.com/net-ssh/net-ssh/issues/511

**Comment by mccont** [comment]
Yeah, there is a very specific net/ssh release which works with the older Ruby releases that you need to use because of a bug in the default release. 

You can install the right specific versions using: 

gem install net-ssh -v 2.5.2
gem install net-scp -v 1.0.4

**Comment by yambrosov** [comment]
I tested with 
gem install net-ssh -v 2.5.2
gem install net-scp -v 1.0.4

The same: works from pytty, "SSHKit::Command::Failed: cd exit status: 1" from net-ssh

**Comment by mccont** [comment]
It's still an issue with SSH rather the tungsten code. 

What Ruby version is this? And the operating system?

**Comment by yambrosov** [comment]
Yes, we can close this issue, problem is in net-ssh library (https://github.com/net-ssh/net-ssh/issues/511).

1.1) win10 (ruby 2.3, net-ssh 4.1.0)
1.2) win10 (putty)
2.1) node1-deb8 (ruby 2.0, net-ssh 4.1.0) - installing tungstem from here, uses net-ssh internally to connect to node2
2.2) node2-deb8 (ruby 2.0, net-ssh 4.1.0)


win10 (putty) -> node1-deb8 (ruby 2.0, net-ssh 4.1.0) -> node1-deb8 (ruby 2.0, net-ssh 4.1.0)
Connection OK

If i start the same from 1.1) win10 (ruby 2.3, net-ssh 4.1.0) - error

**Comment by mcbguru** [comment]
Thanks for the extra detail - looking at the net/ssh issue you filed, I could see how the coimbination of the password in one connection and pubkey in the other could confuse the entire process. 

I'll close, but feel free to report any further issues - we're aware of the complex compatibility between Ruby and net/ssh versions.
