### ISSUE TITLE
Some problems 

### ISSUE THREAD

**Issue by peng19832** [continuent/tungsten-replicator#5]
OS: Centos 7
java version: 1.8.0_144
Ant(TM) version: 1.9.9

execute ./tools/tpm --help
ERROR >> Unable to read .manifest file: Unable to parse the .manifest.json file

**Comment by supersujj** [comment]
i have the same problem,can you fix it?

**Comment by mccont** [comment]
You need to build the software first, or use one of the available tarballs. You cannot install directly from the Github repository.

Build instructions are in the README for this project.
