### ISSUE TITLE
Provisioning Fails when field names have spaces in them.

### ISSUE THREAD

**Issue by RobVor** [continuent/tungsten-replicator#7]
Good Day,

When provisioning a database the process fails when the table field names have spaces in them.

I loaded up 2 virtual machines with Tungsten (Master Master mode), populated an old databases on one of the 2 servers and tried to do provisioning to test the functionality.

The process fails with:

ERROR ParallelExtractorThread SQL failed : SELECT ID, fk_RewardsID, Rewards Description FROM `MyRewards`.`BankRewards` WHERE ID > 1999 AND ID <= 2968 ORDER BY ID
java.sql.SQLSyntaxErrorException: Unknown column 'Rewards' in 'field list'
        at org.drizzle.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:99)
        at org.drizzle.jdbc.DrizzlePreparedStatement.executeQuery(DrizzlePreparedStatement.java:105)
        at com.continuent.tungsten.replicator.extractor.parallel.ParallelExtractorThread.runTask(ParallelExtractorThread.java:202)
        at com.continuent.tungsten.replicator.extractor.parallel.ParallelExtractorThread.run(ParallelExtractorThread.java:107)
Caused by: org.drizzle.jdbc.internal.common.QueryException: Unknown column 'Rewards' in 'field list'
        at org.drizzle.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:464)
        at org.drizzle.jdbc.DrizzlePreparedStatement.executeQuery(DrizzlePreparedStatement.java:102)

Obviously it can't find the column Rewards, because it doesn't exist. 'Rewards Description' does.

The from clause selects the tables correctly (Placing them in quotes such as 'MyRewards'.'BankRewards...') but the fields are not selected the same way. Instead of  SELECT fk_RewardsID, Rewards Description... it should be SELECT 'fk_RewardsID', 'Rewards Description' ...

**Comment by mccont** [comment]
Hi. 

Having spaces in column or table names is generally considered bad practice. If you want a separator, you should use the underscore. 

While spaces in column names and other identifiers is allowed, they are not a good idea. 

MC

**Comment by RobVor** [comment]
Not really an answer for a 20 year old fully functional mainframe system
and database(s)

Changing this would require an update and rework of no less than 12 front
ends (excluding web) and 2.8 million clients in 8 countries for over 400
companies.

**Comment by mccont** [comment]
You've set up a brand new Master Master service that is 20 years old? 

If you've loaded the data from an old mainframe system, why are you provisioning from one MySQL master to another, why not just provision both with the dump you created?  

Furthermore, provisioning on MySQL is unsupported - the provisioning built into the system is designed for Oracle and not MySQL environments. Provisioning from MySQL should be completed with tungsten_provision_slave or tungsten_provision_thl.

**Comment by mccont** [comment]
You've set up a brand new Master Master service that is 20 years old? 

If you've loaded the data from an old mainframe system, why are you provisioning from one MySQL master to another, why not just provision both with the dump you created?  

Furthermore, provisioning on MySQL is unsupported - the provisioning built into the system is designed for Oracle and not MySQL environments.

**Comment by RobVor** [comment]
It is know as a 'lab' a test run. You would benefit from learning the
difference. You never try something new on existing systems. (And
especially not when it is this flaky.)

Secondly, your documentation does not state this, as a mater of fact it is
sorely lacking.

Thirdly, I have actually been trying to find reasons to justify the puchase
of this, which includes disaster recovery, something to make life easier,
which this clearly does not do.

Nevermind, this is just turning into a bigger and bigger disappointment.

I have seen enough, and heard enough to know this won't improve, heaven
knows why it is touted as such a miracle system.

I'll create my own application, troubleshooting this has taught me enough
already.

Thank you.


On 12 Sep 2017 6:15 PM, "MC Brown" <notifications@github.com> wrote:

You've set up a brand new Master Master service that is 20 years old?

If you've loaded the data from an old mainframe system, why are you
provisioning from one MySQL master to another, why not just provision both
with the dump you created?

Furthermore, provisioning on MySQL is unsupported - the provisioning built
into the system is designed for Oracle and not MySQL environments.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/continuent/tungsten-replicator/issues/7#issuecomment-328903634>,
or mute the thread
