### ISSUE TITLE
Wrong reference to s3 config file

### ISSUE THREAD

**Issue by tiagopadua** [continuent/tungsten-replicator#8]
Hello,

I was trying to configure a MySQL to RedShift replication, and I believe I found a bug.

The replicator cannot find my S3 configuration file.
Just to confirm, my S3 configuration file is located at ```/opt/continuent/share/s3-config-alpha.json```, and all my base configurations are using *--install-directory=/opt/continuent*.

But I'm getting the following error:
```
pendingExceptionMessage: Unable to prepare plugin: class name=com.continuent.tungsten.replicator.applier.ApplierWrapper message=[com.continuent.tungsten.replicator.ReplicatorException: AWS S3 configuration file (share/s3-config-alpha.json (/opt/continuent/tungsten/tungsten-replicator/appliers/batch/redshift.js#43)]
```

While investigating it, I found this line of code:
https://github.com/continuent/tungsten-replicator/blob/12042374c94a6534dbf372418d9514a956820639/replicator/appliers/batch/redshift.js#L35

The relative path on the code above seems to be ***wrong***.

I changed it to ```"../../share/" + awsConfigFileName;``` and the error is gone! (pay attention to the number of ```../``` relative paths)

# Version used

I'm using Tungsten Replicator version 5.0.1

I cloned the repository and built it today (September 18, 2017).

# deploy.cfg
```
# Tungsten configuration properties
# Date: 2017-09-18T17:00:06+00:00
{
  "dataservice_host_options": {
    "alpha": {
      "home_directory": "/opt/continuent",
      "root_command_prefix": "true",
      "skipped_validation_classes": [
        "MySQLMyISAMCheck"
      ]
    }
  },
  "dataservice_replication_options": {
    "alpha": {
      "enable_heterogenous_service": "true"
    }
  },
  "dataservices": {
    "alpha": {
      "dataservice_hosts": "tmaster,tslave",
      "dataservice_master_host": "tmaster",
      "dataservice_name": "alpha"
    }
  },
  "hosts": {
    "tslave": {
      "host_name": "tslave",
      "skipped_validation_classes": [
        "MySQLMyISAMCheck"
      ]
    },
    "tmaster": {
      "host_name": "tmaster",
      "skipped_validation_classes": [
        "MySQLMyISAMCheck"
      ]
    }
  },
  "repl_services": {
    "alpha_tslave": {
      "batch_enabled": "true",
      "batch_load_template": "redshift",
      "deployment_dataservice": "alpha",
      "deployment_host": "tslave",
      "repl_datasource_host": "replicator.*****.us-east-2.redshift.amazonaws.com",
      "repl_datasource_password": "*****",
      "repl_datasource_type": "redshift",
      "repl_datasource_user": "tungsten",
      "repl_redshift_dbname": "dev",
      "repl_svc_applier_block_commit_interval": "10s",
      "repl_svc_applier_block_commit_size": "5",
      "repl_svc_applier_filters": "dropstatementdata"
    },
    "alpha_tmaster": {
      "deployment_dataservice": "alpha",
      "deployment_host": "tmaster",
      "fixed_property_strings": [
        "replicator.filter.pkey.addColumnsToDeletes=true",
        "replicator.filter.pkey.addPkeyToInserts=true"
      ],
      "repl_datasource_password": "tungsten",
      "repl_datasource_user": "*****"
    }
  }
}

```

**Comment by mccont** [comment]
Hi,

Yes, we've noticed this and it will be in a future update. We're in the
process of updating and pushing new content and support into Github at the
moment. Until then, please feel free to edit by hand.

**Comment by tiagopadua** [comment]
Closing the issue, as I see this was resolved on [this commit](https://github.com/continuent/tungsten-replicator/commit/4a2d84abf549041a8536e105fb324a8f3ca4fdea).
